language: python
sudo: false
python:
  - "2.7"
addons:
  firefox: "46.0.1"
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "python setup.py install"
before_script:
  - "flake8 masterqa/*.py"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "firefox --version"
script:
  - "nosetests examples/deploy_only/results_page.py --with-selenium --browser=firefox"
  - "pytest examples/deploy_only/results_page.py --with-selenium --browser=firefox"
env:
  matrix:
  - BROWSER=firefox
notifications:
  email: false
